default:
  assessment_db: database.sqlite
  credential_db: credentials.sqlite
  loggit_json: loggit.json
  credentials:
    roles:
      - admin
      - lead
      - reviewer
    privileges:
      admin: admin
      reweighting: lead
      final_decision: lead
      revert_decision: lead
      add_package: [lead, reviewer]
      delete_package: lead
  decisions:
    categories:
      - Low Risk
      - Medium Risk
      - High Risk
  metric_weights:
    covr_coverage: 0
example:
  assessment_db: database_ex.sqlite
  decisions:
    categories:
      - Insignificant Risk
      - Minor Risk
      - Moderate Risk
      - Major Risk
      - Severe Risk
    rules:
      Insignificant Risk:
        - 0
        - .1
      Severe Risk:
        - .7
        - 1
    colors:
      Moderate Risk: !expr grDevices::rgb(52, 235, 229, maxColorValue = 255)
  metric_weights:
    covr_coverage:
    has_vignettes: 2
example2:
  assessment_db: database_ex2.sqlite
  decisions:
    categories:
      - GxP Compliant
      - Needs Review
      - Not GxP Compliant
