default:
  assessment_db: database.sqlite
  credential_db: credentials.sqlite
  credentials:
    roles:
      - admin
      - lead
      - reviewer
    privileges:
      admin: admin
      reweighting: lead
      final_decision: lead
      revert_decision: lead
      add_package: [lead, reviewer]
      delete_package: lead
  decision_categories:
    - Low Risk
    - Medium Risk
    - High Risk
example:
  assessment_db: database_ex.sqlite
  decision_categories:
    - Insignificant Risk
    - Minor Risk
    - Moderate Risk
    - Major Risk
    - Severe Risk
  decision_rules:
    Insignificant Risk:
      - 0
      - .1
    Severe Risk:
      - .7
      - 1
example2:
  assessment_db: database_ex2.sqlite
  decision_categories:
    - GxP Compliant
    - Needs Review
    - Not GxP Compliant
