default:
  assessment_db: database.sqlite
  credential_db: credentials.sqlite
  loggit_json: loggit.json
  credentials:
    roles:
      - admin
      - lead
      - reviewer
    privileges:
      admin: admin
      tier1: lead
      tier2: reviewer
  decisions:
    categories:
      - Low Risk
      - Medium Risk
      - High Risk
example:
  assessment_db: database_ex.sqlite
  credential_db: credentials_ex.sqlite
  credentials:
    roles:
      - admin
      - reweighter
      - decider
      - reverter
      - adder
      - deleter
    privileges:
      admin: admin
      tier1:
      tier2:
      weight_adjust: reweighter
      decision_adjust: reweighter
      final_decision: [decider, reverter]
      revert_decision: reverter
      add_package: [adder, deleter]
      delete_package: deleter
  decisions:
    categories:
      - Insignificant Risk
      - Minor Risk
      - Moderate Risk
      - Major Risk
      - Severe Risk
    rules:
      Insignificant Risk:
        - 0
        - .1
      Severe Risk:
        - .7
        - 1
    colors:
      Moderate Risk: !expr grDevices::rgb(52, 235, 229, maxColorValue = 255)
example2:
  assessment_db: database_ex2.sqlite
  credential_db: credentials_ex2.sqlite
  decisions:
    categories:
      - GxP Compliant
      - Needs Review
      - Not GxP Compliant
