# Workflow derived from https://solutions.posit.co/operations/deploy-methods/ci-cd/github-actions/#overview-of-deploying-to-connect

name: write-manifest
on:
  pull_request_review:
    branches: [dev]
    type: [submitted]
  

jobs:
  write-manifest:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2

      - name: Install required packages
        run: Rscript -e 'install.packages("rsconnect")'

      - name: Create manifest.json
        run: Rscript -e 'rsconnect::writeManifest()'
          
      - name: Commit results
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "actions@github.com"
          if git merge-base --is-ancestor dev @
          then
            echo "Branch is up to date"
          else
            echo "::error:: Branch is NOT up to date with dev"
            exit 1
          fi
          git add manifest.json || echo "WARN: manifest.json was not updated"
          git commit -m 'Re-build manifest file' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
